# Generated by Django 5.0.6 on 2026-01-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
