# Generated by Django 5.0.6 on 2026-05-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackage',
            name='upgrade',
            field=models.TextField(blank=True, null=True),
        ),
    ]
