# Generated by Django 5.0.6 on 2026-07-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_orderpackage_upgrade'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("SET FOREIGN_KEY_CHECKS = 0;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_cldetail`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_clrelease`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_claimrelease`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_programrelease`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_proposalrelease`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_incrementalsales`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_projectedcost`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_budgetrelease`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_budgetdetail`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_areachanneldetail`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_areasalesdetail`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_budgetapproval`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_claimmatrix`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_clmatrix`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_programmatrix`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_proposalmatrix`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_claim`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_cl`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_program`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_proposal`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_budget`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_areachannel`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_channel`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_distributor`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_division`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_closing`;"),
                migrations.RunSQL("DROP TABLE IF EXISTS `apps_uploadlog`;"),
                migrations.RunSQL("SET FOREIGN_KEY_CHECKS = 1;"),
            ],
            state_operations=[
                migrations.DeleteModel(name='CLDetail'),
                migrations.DeleteModel(name='CLRelease'),
                migrations.DeleteModel(name='ClaimRelease'),
                migrations.DeleteModel(name='ProgramRelease'),
                migrations.DeleteModel(name='ProposalRelease'),
                migrations.DeleteModel(name='IncrementalSales'),
                migrations.DeleteModel(name='ProjectedCost'),
                migrations.DeleteModel(name='BudgetRelease'),
                migrations.DeleteModel(name='BudgetDetail'),
                migrations.DeleteModel(name='AreaChannelDetail'),
                migrations.DeleteModel(name='AreaSalesDetail'),
                migrations.DeleteModel(name='BudgetApproval'),
                migrations.DeleteModel(name='ClaimMatrix'),
                migrations.DeleteModel(name='CLMatrix'),
                migrations.DeleteModel(name='ProgramMatrix'),
                migrations.DeleteModel(name='ProposalMatrix'),
                migrations.DeleteModel(name='Claim'),
                migrations.DeleteModel(name='CL'),
                migrations.DeleteModel(name='Program'),
                migrations.DeleteModel(name='Proposal'),
                migrations.DeleteModel(name='Budget'),
                migrations.DeleteModel(name='AreaChannel'),
                migrations.DeleteModel(name='Channel'),
                migrations.DeleteModel(name='Distributor'),
                migrations.DeleteModel(name='Division'),
                migrations.DeleteModel(name='Closing'),
                migrations.DeleteModel(name='UploadLog'),
            ],
        ),
    ]
