# Generated by Django 5.0.6 on 2026-07-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_areachanneldetail_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoatType',
            fields=[
                ('goat_type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('goat_type_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='goat_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.goattype'),
        ),
    ]
