# Generated by Django 5.0.6 on 2026-07-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_goattype_package_goat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='departure_time',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='schedule_status',
            field=models.CharField(default='UNSCHEDULED', max_length=20),
        ),
    ]
