# Generated by Django 5.0.6 on 2026-07-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_add_schedule_fields_to_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dashboard_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(null=True)),
                ('entry_by', models.CharField(max_length=50, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.dashboard'),
        ),
    ]
