# Generated by Django 5.0.6 on 2026-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_maincuisine_porsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcuisine',
            name='porsi',
            field=models.IntegerField(default=0),
        ),
    ]
