# Generated by Django 5.0.6 on 2026-07-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_add_tipe_to_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='tipe',
            field=models.CharField(blank=True, choices=[('', '-- Pilih Tipe --'), ('Kemasan Dan Souvenir', 'Kemasan Dan Souvenir'), ('Masakan', 'Masakan'), ('Olahan Dan Pendamping', 'Olahan Dan Pendamping'), ('Box Paket', 'Box Paket')], max_length=50, null=True),
        ),
    ]
