# Generated by Django 5.0.6 on 2026-07-24 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_update_tipe_olahan_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='goat_type2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_goat_type2', to='apps.goattype'),
        ),
    ]
